import math

RES = WITDH, HEIGHT = 1920, 1080
HALF_WITDH = WITDH // 2
HALF_HEIGHT = HEIGHT //2
FPS = 60

PLAYER_POS = 1.5 , 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.005
PLAYER_ROT_SPEED = 0.003
PLAYER_SIZE_SCALE = 10
PLAYER_MAX_HP = 100

MOUSE_SENS = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WITDH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WITDH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WITDH / math.tan(HALF_FOV)
SCALE = WITDH // NUM_RAYS

TEXTURE_SIZE = 512
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2