import math

RES = WITDH, HEIGHT = 1300, 700
HALF_WITDH = WITDH // 2
HALF_HEIGHT = HEIGHT //2
FPS = 0

PLAYER_POS = 1.5 , 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.002
PLAYER_ROT_SPEED = 0.001

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WITDH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WITDH / math.tan(HALF_FOV)
SCALE = WITDH // NUM_RAYS